version: '3.8'

services:
  backend:
    image: your-dockerhub-username/courses-backend
    ports:
      - "8000:8000"

  frontend:
    image: your-dockerhub-username/courses-frontend
    ports:
      - "3000:3000"
